name: Backup

on:
  push:
    branches: [ '*' ]
  schedule:
    - cron:  '0 4 * * *'

jobs:
  backup:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:3.6
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Create and download database dump
        run: ./download-database.sh
      - name: Restore database dump
        run: docker run --tty --name jude-mongo --add-host=host.docker.internal:host-gateway -v $PWD:/tmp mongo:3.6 mongorestore --host host.docker.internal --drop --gzip --archive=/tmp/bocamongo.gz
        
      - name: Archive database dump
        uses: actions/upload-artifact@v2
        with:
          name: bocamongo
          path: bocamongo.gz
          retention-days: 21
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - run: node query-scores.js > scores.json
      - run: node upload-scores.js
        env:
          GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      - name: Archive score
        uses: actions/upload-artifact@v2
        with:
          retention-days: 21
          name: scores
          path: scores.json

