name: Backup

on:
  push:
    branches: [ '*' ]
  schedule:
    - cron:  '0 4 * * *'

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - run: ./download-database.sh
      - uses: actions/upload-artifact@v2
        with:
          name: bocamongo
          path: bocamongo.gz

